{
 "title": "Flask App – RED + Pods",
 "tags": [ "flask" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (method, status) (rate(flask_http_request_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Duration (p95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le, path) (rate(flask_http_request_duration_seconds_bucket[5m]))\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (pod) (\r\n  rate(container_cpu_usage_seconds_total{pod=~\"flask.*\"}[5m])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (\r\n  container_memory_usage_bytes{pod=~\"flask.*\"}\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Restarts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 8 },
   "targets": [
    {
     "expr": "sum by (pod) (\r\n  rate(kube_pod_container_status_restarts_total{pod=~\"flask.*\"}[5m])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}