grafana:
  enabled: true
  adminPassword: "admin123"
  service:
    type: NodePort

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorNamespaceSelector: {}
    serviceMonitorSelector: {}

alertmanager:
  enabled: true